export default {
    Module: `import {Module} from 'node:module'`,
    SourceMap: `import {SourceMap} from 'node:module'`,
    builtinModules: `import {builtinModules} from 'node:module'`,
    constants: `import {constants} from 'node:module'`,
    createRequire: `import {createRequire} from 'node:module'`,
    enableCompileCache: `import {enableCompileCache} from 'node:module'`,
    findPackageJSON: `import {findPackageJSON} from 'node:module'`,
    findSourceMap: `import {findSourceMap} from 'node:module'`,
    flushCompileCache: `import {flushCompileCache} from 'node:module'`,
    getCompileCacheDir: `import {getCompileCacheDir} from 'node:module'`,
    getSourceMapsSupport: `import {getSourceMapsSupport} from 'node:module'`,
    globalPaths: `import {globalPaths} from 'node:module'`,
    isBuiltin: `import {isBuiltin} from 'node:module'`,
    register: `import {register} from 'node:module'`,
    registerHooks: `import {registerHooks} from 'node:module'`,
    runMain: `import {runMain} from 'node:module'`,
    setSourceMapsSupport: `import {setSourceMapsSupport} from 'node:module'`,
    stripTypeScriptTypes: `import {stripTypeScriptTypes} from 'node:module'`,
    syncBuiltinESMExports: `import {syncBuiltinESMExports} from 'node:module'`,
};
