export default {
    arch: `import {arch} from 'node:os'`,
    cpus: `import {cpus} from 'node:os'`,
    endianness: `import {endianness} from 'node:os'`,
    freemem: `import {freemem} from 'node:os'`,
    getPriority: `import {getPriority} from 'node:os'`,
    homedir: `import {homedir} from 'node:os'`,
    hostname: `import {hostname} from 'node:os'`,
    loadavg: `import {loadavg} from 'node:os'`,
    networkInterfaces: `import {networkInterfaces} from 'node:os'`,
    platform: `import {platform} from 'node:os'`,
    release: `import {release} from 'node:os'`,
    setPriority: `import {setPriority} from 'node:os'`,
    tmpdir: `import {tmpdir} from 'node:os'`,
    totalmem: `import {totalmem} from 'node:os'`,
    userInfo: `import {userInfo} from 'node:os'`,
    uptime: `import {uptime} from 'node:os'`,
    constants: `import {constants} from 'node:os'`,
    EOL: `import {EOL} from 'node:os'`,
    devNull: `import {devNull} from 'node:os'`,
};
