export default {
    resolve: `import {resolve} from 'node:path'`,
    normalize: `import {normalize} from 'node:path'`,
    isAbsolute: `import {isAbsolute} from 'node:path'`,
    join: `import {join} from 'node:path'`,
    relative: `import {relative} from 'node:path'`,
    toNamespacedPath: `import {toNamespacedPath} from 'node:path'`,
    dirname: `import {dirname} from 'node:path'`,
    basename: `import {basename} from 'node:path'`,
    extname: `import {extname} from 'node:path'`,
    format: `import {format} from 'node:path'`,
    sep: `import {sep} from 'node:path'`,
    delimiter: `import {delimiter} from 'node:path'`,
    win32: `import {win32} from 'node:path'`,
    posix: `import {posix} from 'node:path'`,
};
