export default {
    findFile: 'const {findFile} = operator',
    findFileUp: 'const {findFileUp} = operator',
    renameFile: 'const {renameFile} = operator',
    renameFiles: 'const {renameFiles} = operator',
    removeFile: 'const {removeFile} = operator',
    moveFile: 'const {moveFile} = operator',
    createFile: 'const {createFile} = operator',
    createDirectory: 'const {createDirectory} = operator',
    createNestedDirectory: 'const {createNestedDirectory} = operator',
    getFilename: 'const {getFilename} = operator',
    getFileType: 'const {getFileType} = operator',
    getParentDirectory: 'const {getParentDirectory} = operator',
    getRootDirectory: 'const {getRootDirectory} = operator',
    readFileContent: 'const {readFileContent} = operator',
    writeFileContent: 'const {writeFileContent} = operator',
    copyFile: 'const {copyFile} = operator',
    readDirectory: 'const {readDirectory} = operator',
    removeEmptyDirectory: 'const {removeEmptyDirectory} = operator',
};
