'use strict';

module.exports = {
    OK: 0,
    PLACE: 1,
    STAGE: 2,
    NO_FILES: 3,
    NO_PROCESSORS: 4,
    NO_FORMATTER: 5,
    WAS_STOP: 6,
    INVALID_OPTION: 7,
    CANNOT_LOAD_PROCESSOR: 8,
    CANNOT_LOAD_FORMATTER: 9,
    RULER_WITH_FIX: 10,
    RULER_NO_FILES: 11,
    INVALID_CONFIG: 12,
    UNHANDLED: 13,
    CANNOT_LINT_STAGED: 14,
    INTERACTIVE_CANCELED: 15,
};
