name: Node PR CI
permissions:
  contents: write
on:
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NAME: putout
    strategy:
      matrix:
        node-version:
          - 22.x
          - 24.x
          - 26.x
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Redrun
        run: bun install redrun madrun -g --no-save
      - name: Install
        run: bun install -f
      - name: Init Madrun
        run: madrun --init
      - name: Lint
        run: redrun lint
      - name: Typos
        uses: coderaiser/typos.ai@v1.1.8
        with:
          key: ${{ secrets.TYPOS_AI_KEY }}
      - name: Coverage
        run: redrun coverage report
